name: 'Zai Code Bot'
description: 'AI-powered PR code review'
author: 'AndreiDrang'
branding:
  icon: 'shield'
  color: 'blue'
inputs:
  ZAI_API_KEY:
    description: "Z.ai API key"
    required: true
  ZAI_MODEL:
    description: "Z.ai AI model"
    required: false
    default: "glm-5"
  GITHUB_TOKEN:
    description: "GitHub token for API access"
    required: false
    default: ${{ github.token }}
  ZAI_TIMEOUT:
    description: "Z.ai API request timeout in milliseconds"
    required: false
    default: "30000"
runs:
  using: "node20"
  main: "dist/index.js"
