/**
 * Build script: reads human-authored prompt text files from `prompts/` and emits
 * importable JS modules under `generated/`. Each prompt becomes
 * `export const <NAME> = "<json-stringified text>";`.
 *
 * Pattern adapted from tb-news-ai-analyzer/scripts/generate-prompt.mjs.
 *
 * The generated files are committed so `wrangler deploy` works without a
 * prebuild step. Re-run this
 * script whenever a `.txt` prompt changes:
 *
 *     npm run generate:prompts
 *
 * Adding a new prompt: drop a `prompts/<name>.txt`, add an entry to `PROMPTS`
 * below, run the script, and commit the new `generated/*.js` file.
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const promptsDir = path.resolve(__dirname, '../prompts');
const outputDir = path.resolve(__dirname, '../generated');

// One entry per prompt. `constName` is the exported identifier handlers import.
const PROMPTS = [
  { input: 'review.txt', output: 'prompts.js', constName: 'REVIEW_PROMPT' },
  { input: 'pr-summary.txt', output: 'prompts.js', constName: 'PR_SUMMARY_PROMPT' },
];

await fs.mkdir(outputDir, { recursive: true });

const generated = new Map();
for (const { input, output, constName } of PROMPTS) {
  const promptPath = path.join(promptsDir, input);
  const prompt = await fs.readFile(promptPath, 'utf8');
  const entries = generated.get(output) || [];
  entries.push({
    input,
    constName,
    prompt,
    source: ` * Source: prompts/${input}`,
  });
  generated.set(output, entries);
}

for (const [output, entries] of generated) {
  const outputPath = path.join(outputDir, output);
  const sources = entries.map((entry) => entry.source).join('\n');
  const header =
    '/**\n * AUTO-GENERATED by scripts/generate-prompts.mjs — do not edit by hand.\n' +
    `${sources}\n */\n`;
  const content =
    header +
    entries.map((entry) => `export const ${entry.constName} = ${JSON.stringify(entry.prompt)};\n`).join('');

  await fs.writeFile(outputPath, content, 'utf8');
  for (const entry of entries) {
    // eslint-disable-next-line no-console
    console.log(`generated/${output}: ${entry.constName} (${entry.prompt.length} chars)`);
  }
}
